_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: 12
  ROI_BOX_HEAD:
    FED_LOSS_NUM_CLASSES: 12
  ROI_HEADS:
    NUM_CLASSES: 12
DATASETS:
  TRAIN: ("tt100k_aug_balance",)
  TEST: ("sustech",)
SOLVER:
  IMS_PER_BATCH: 4
  MAX_ITER: 50000
  STEPS:
  - 37000
  - 43000
  BASE_LR: 0.001
TEST:
  EVAL_PERIOD: 2000